name: PHP Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
      
    - name: first
      run: git remote -v

    - name: second
      run: ssh-add ~/.ssh/id_rsa

     
    - name: Deploy to production
      run:  git remote set-url origin git@github.com:sallyfoong/darzenfc-live.git
      
    - name: done push
      run:  git push origin
      
      
    - name: done pull
      run:  git pull origin

      



