name: Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # Replace with your build or dependency installation commands

    - name: Build project
      run: npm run build  # Replace with your build command

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        server-ip: 101.99.70.222
        server-username: darzenfc
        local-path: /home/darzenfc/public_html/cms/live  # Replace with the path to your build artifacts or deployment files
        remote-path: https://github.com/sallyfoong/darzenfc-live  # Replace with the remote path where you want to deploy your code
